import type { Metadata } from "next";
// import { Inter } from "next/font/google"; // ← 1. この行をコメントアウト（または削除）
import "./globals.css";
import { SettingsProvider } from "@/contexts/SettingsContext";
import { ImageProvider } from "@/contexts/ImageContext";

// const inter = Inter({ subsets: ["latin"] }); // ← 2. この行もコメントアウト（または削除）

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        {/*この一行がレスポンシブ対応に絶対に必要 */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <SettingsProvider>
          <ImageProvider>
            {children}
          </ImageProvider>
        </SettingsProvider>
        </body>
    </html>
  );
}
