import type { Metadata } from "next";
// import { Inter } from "next/font/google"; // ← 1. この行をコメントアウト（または削除）
import "./globals.css";
import { SettingsProvider } from "@/contexts/SettingsContext";

// const inter = Inter({ subsets: ["latin"] }); // ← 2. この行もコメントアウト（または削除）

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* ↓ 3. bodyタグから className={inter.className} を削除 */}
      <body>
        <SettingsProvider>
          {children}
        </SettingsProvider></body>
    </html>
  );
}
